### ISSUE TITLE
PerfectPixel

### ISSUE THREAD

**Issue by Sha1fei** [KatePronina/UI-kit#1]
Нужно чтобы основной макет был выполнен по PixelPerfect,  как сделаешь выложи здесь плиз скрин в инверсии с параметрами чтобы можно было отследить расхождения, и обнови github pages ( там насколько помню исходик сильно большой можешь смасштабировать, чтобы лучше смотрелось)

**Comment by KatePronina** [comment]
Переверстала по макету
В некоторых местах немного отошла от него
Например, в блоке с диаграммами на макете у каждой диаграммы разные отступы от соседних, я сделала одинаковое расстояние между ними, т.к. это более логично, могу исправить на разные, если совсем как на макете отступы нужны
![FireShot Capture 005 - Index - localhost](https://user-images.githubusercontent.com/25391680/63636720-bb782100-c67b-11e9-986e-178e23b3708a.png)
![joxi_screenshot_11settings](https://user-images.githubusercontent.com/25391680/63636722-cc289700-c67b-11e9-8133-b3c599ae6f36.png)
