### ISSUE TITLE
импорт

### ISSUE THREAD

**Issue by Sha1fei** [KatePronina/UI-kit#13]
![Screenshot 2019-08-24 at 15 52 36](https://user-images.githubusercontent.com/31854808/63634956-3a268b80-c687-11e9-928a-66635fb19d16.png)
Импорть js аналогично)

**Comment by KatePronina** [comment]
Про js хотела уточнить, а нужно ли его так импортировать везде?) Ведь все js файлы нужны только для станицы со всеми элементами ui-kit
А на странице реального сайта из js-элементов могут быть, например, только карта и слайдер, соответственно, только js карты и слайдера нужно импортировать или все равно весь js?

**Comment by Sha1fei** [comment]
Да, ты все верно описала, я и имел ввиду UI-kit, у тебя под отдельные импорты для разных страниц уже реализован в вебпаке code splitting)
![Снимок экрана от 2019-08-26 08-43-07](https://user-images.githubusercontent.com/31854808/63659791-93a0ce80-c7dd-11e9-8c0d-16a158f82fc2.png)
