### ISSUE TITLE
SCSS

### ISSUE THREAD

**Issue by Sha1fei** [KatePronina/UI-kit#20]
в fundamental.scss нужно оставить стили только для тэгов  html bode.  Класс .visually-hidden разнести по блокам, для .wrapper предусмотреть отдельный файл.
Мы не используем миксы, на риззоме есть обсуждение на эту тему.
![Снимок экрана от 2019-09-05 12-53-34](https://user-images.githubusercontent.com/31854808/64315474-535efe80-cfdc-11e9-85f4-2215d55a67d2.png)
![Снимок экрана от 2019-09-05 12-53-45](https://user-images.githubusercontent.com/31854808/64315475-535efe80-cfdc-11e9-8733-6bd7e45c2582.png)
![Снимок экрана от 2019-09-05 13-41-34](https://user-images.githubusercontent.com/31854808/64317845-f61a7b80-cfe2-11e9-9a8c-9977744f15b8.png)
![Снимок экрана от 2019-09-05 13-47-09](https://user-images.githubusercontent.com/31854808/64318209-b99b4f80-cfe3-11e9-9a22-ff3cdfe9c4ba.png)
![Снимок экрана от 2019-09-05 13-55-00](https://user-images.githubusercontent.com/31854808/64318684-cff5db00-cfe4-11e9-85be-b2a0c01a02fe.png)
.arrow-buttonsтут модификаторы  fill b prev  не по БЭМу, fill  лучше использовать что то вроде _theme_green, prev => _direction_left. Это развяжет руки если будет расширение цветовой гаммы к примеру.
Для  .button  аналогичные замечания.
.ui-datepicker-header, .ui-selectmenu-menu, .ui-slider-handle все сторонние стили нужно вынести в папку vendor (
используй возможности препроцессоров  не дублируй именования)
Тут неудачные именования - нужно придумать другие
![Снимок экрана от 2019-09-05 13-31-51](https://user-images.githubusercontent.com/31854808/64317351-a25b6280-cfe1-11e9-812f-4f61d018ff3f.png)
тут  тоже reply - это глагол, а элемент должен быть существительным
![Снимок экрана от 2019-09-05 13-34-15](https://user-images.githubusercontent.com/31854808/64317555-47763b00-cfe2-11e9-91e7-811cebe511d7.png)
![Снимок экрана от 2019-09-05 13-48-37](https://user-images.githubusercontent.com/31854808/64318265-e3547680-cfe3-11e9-8f35-99d29260428b.png)

**Comment by KatePronina** [comment]
У "reply" два значения, одно из которых существительное
Переименовала на вариант с одним значением

**Comment by Sha1fei** [comment]
Ты не подправила первые 4- картинки. Здесь нужно оформить код согласно БЭМ. 
![Снимок экрана от 2019-09-06 14-08-51](https://user-images.githubusercontent.com/31854808/64408087-195f2c80-d0b0-11e9-8507-187713ce13da.png)

**Comment by Sha1fei** [comment]
Тут тоже нет необходимости дублировать код) 
![Снимок экрана от 2019-09-06 14-12-58](https://user-images.githubusercontent.com/31854808/64408262-7d81f080-d0b0-11e9-800e-ed8db3752a07.png)

**Comment by Sha1fei** [comment]
Тут необходимо избавиться от миксина.
![Снимок экрана от 2019-09-09 08-31-51](https://user-images.githubusercontent.com/31854808/64498079-f2d20900-d2dc-11e9-8142-ecc4e41f848e.png)
Используй точечную нотацию где это возможно
![Снимок экрана от 2019-09-09 09-42-40](https://user-images.githubusercontent.com/31854808/64500142-32e9b980-d2e6-11e9-98ec-94b6c4223dcb.png)
![Снимок экрана от 2019-09-09 08-52-46](https://user-images.githubusercontent.com/31854808/64498593-5c531700-d2df-11e9-8bfc-4a9f50a0d77f.png)
![Снимок экрана от 2019-09-09 08-52-53](https://user-images.githubusercontent.com/31854808/64498595-5c531700-d2df-11e9-898d-4dbe220fde7f.png)
![Снимок экрана от 2019-09-09 08-53-02](https://user-images.githubusercontent.com/31854808/64498596-5cebad80-d2df-11e9-9925-43a808c3bd31.png)
![Снимок экрана от 2019-09-09 08-53-16](https://user-images.githubusercontent.com/31854808/64498597-5cebad80-d2df-11e9-92b4-4374650370e0.png)
![Снимок экрана от 2019-09-09 09-03-38](https://user-images.githubusercontent.com/31854808/64498875-c0c2a600-d2e0-11e9-993b-05c637c8bfb0.png)
![Снимок экрана от 2019-09-09 09-04-35](https://user-images.githubusercontent.com/31854808/64498900-e18afb80-d2e0-11e9-9f48-ef474a885f72.png)
![Снимок экрана от 2019-09-09 09-08-50](https://user-images.githubusercontent.com/31854808/64499027-7c83d580-d2e1-11e9-8247-8504a127d490.png)
Добавь плиз ко всем кнопка свойство  cursor: pointer;
По первому макету нужно вынести картинки в отдельную папку
![Снимок экрана от 2019-09-09 08-57-20](https://user-images.githubusercontent.com/31854808/64498691-daafb900-d2df-11e9-8e62-b2e0117add91.png)
Вот здесь если это модификатор то нужно его переименовать к примеру _type_${name}`
![Снимок экрана от 2019-09-09 08-57-49](https://user-images.githubusercontent.com/31854808/64498748-30846100-d2e0-11e9-881e-a8aefea5eee1.png) 

здесь тоже в надо переименовать модификатор в _size_large`
![Снимок экрана от 2019-09-09 09-05-33](https://user-images.githubusercontent.com/31854808/64498984-447c9280-d2e1-11e9-826f-8d62bdcfc86d.png)
тут тоже _theme_error"
![Снимок экрана от 2019-09-09 09-10-14](https://user-images.githubusercontent.com/31854808/64499067-a76e2980-d2e1-11e9-9615-2e03a839c82a.png)
 active => actived
![Снимок экрана от 2019-09-09 09-11-02](https://user-images.githubusercontent.com/31854808/64499141-ff0c9500-d2e1-11e9-8155-4159e480e83c.png)
Тут так и не подправила(не по БЭМу)
![Снимок экрана от 2019-09-09 09-13-14](https://user-images.githubusercontent.com/31854808/64499165-1b103680-d2e2-11e9-802c-292baab4ab13.png)
 тут тоже
![Снимок экрана от 2019-09-09 09-14-16](https://user-images.githubusercontent.com/31854808/64499204-47c44e00-d2e2-11e9-8dda-7385f6a86633.png)
тут стоит переименовать, если дело обстоит в том что средний элемент должен быть другого цвета, то стоит проверять по индексам(по скольку элементы могут меняться и средний не обязательно должен быть твиттером), и менять цвет элемента, к тому же модификатор тут тоже назван не правильно 
![Снимок экрана от 2019-09-09 09-26-56](https://user-images.githubusercontent.com/31854808/64499818-cfab5780-d2e4-11e9-8c6b-c5ed5a641a97.png)
Подправь выше описанные замечания, в целом у меня больше нет замечаний по этому макету)

**Comment by KatePronina** [comment]
Вынесла картинки в отдельную папку в первом проекте, использовала alias

**Comment by KatePronina** [comment]
> тут стоит переименовать, если дело обстоит в том что средний элемент должен быть другого цвета, то стоит проверять по индексам(по скольку элементы могут меняться и средний не обязательно должен быть твиттером), и менять цвет элемента, к тому же модификатор тут тоже назван не правильно

Нет, там в модификаторе не цвет, а размер меняется, т.к. иконка твиттера немного меньше остальных. Когда подгоняла макет для pixel perfect, добавила этой иконке модификатор, чтобы она подходила по размерам как на макете и смотрелась одинаковой по размеру с остальными иконками

**Comment by Sha1fei** [comment]
Нужно подправить 2 вещи:
![Снимок экрана от 2019-09-10 17-00-51](https://user-images.githubusercontent.com/31854808/64605035-7713b180-d3ed-11e9-86fe-b378aa029c1b.png)
вот тут `slider_type_${name}` => `slider-range_type_${name}`
и по поводу модификатора для  твиттера(такое решение не очень, предлагаю добавить 2 модификатора, _color_цвет, и _size_размер.
