### ISSUE TITLE
Деструктуризация, const

### ISSUE THREAD

**Issue by Sha1fei** [KatePronina/UI-kit#3]
Не используй без необходимости let, старайся использовать const. Используй в своих проектах деструктуризацию, она сильно помогает читать код. Вот так можно преобразовать твой блок arrow-button пробегись плиз по всем блокам.
![Screenshot 2019-08-24 at 14 36 02](https://user-images.githubusercontent.com/31854808/63634192-368e0700-c67d-11e9-9637-a99eb17df20f.png)
![Screenshot 2019-08-24 at 14 35 44](https://user-images.githubusercontent.com/31854808/63634193-37269d80-c67d-11e9-9dab-01d939b32628.png)

**Comment by KatePronina** [comment]
Спасибо за пример)
